apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Auth DB
  AUTH_DB_NAME: "auth_db"
  AUTH_DB_USER: "auth"
  AUTH_DB_PASSWORD: "auth"
  # Users DB
  USERS_DB_NAME: "users_db"
  USERS_DB_USER: "users"
  USERS_DB_PASSWORD: "users"
  # Tickets DB
  TICKETS_DB_NAME: "tickets_db"
  TICKETS_DB_USER: "tickets"
  TICKETS_DB_PASSWORD: "tickets"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  AUTH_SV_PORT: "3001"
  USERS_SV_PORT: "3002"
  TICKETS_SV_PORT: "3003"
  # Внутрішні URL для Prisma (використовують імена сервісів K8s)
  AUTH_DATABASE_URL: "postgresql://auth:auth@auth-db-service:5432/auth_db"
  USERS_DATABASE_URL: "postgresql://users:users@users-db-service:5432/users_db"
  TICKETS_DATABASE_URL: "postgresql://tickets:tickets@tickets-db-service:5432/tickets_db"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  USERS_SERVICE_URL: "http://users-service:3002"
  TICKETS_SERVICE_URL: "http://tickets-service:3003"